package main

import (
	"bytes"
	"fmt"
	"html"
	"os"
	"path/filepath"
)

func buildSite(cfg Config) ([]string, error) {
	if err := ensureRootIndexWritable(filepath.Join(cfg.Root, "index.html")); err != nil {
		return nil, err
	}
	if err := ensureNoJekyll(cfg.Root); err != nil {
		return nil, err
	}

	vault, warnings, err := loadVault(cfg)
	if err != nil {
		return warnings, err
	}
	renderVault(vault, &warnings)
	computeBacklinks(vault)

	if err := preparePublic(filepath.Join(cfg.Root, "public")); err != nil {
		return warnings, err
	}
	if err := writeAssets(vault); err != nil {
		return warnings, err
	}
	if err := writePages(vault); err != nil {
		return warnings, err
	}
	if cfg.Search {
		if err := writeSearchIndex(vault); err != nil {
			return warnings, err
		}
	}
	if cfg.Graph {
		if err := writeGraph(vault); err != nil {
			return warnings, err
		}
	}

	return warnings, nil
}

func ensureRootIndexWritable(filename string) error {
	data, err := os.ReadFile(filename)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if bytes.Contains(data, []byte(generatedMarker)) ||
		bytes.Contains(data, []byte(html.EscapeString(generatedMarker))) ||
		isBlankFile(data) {
		return nil
	}
	return fmt.Errorf("%s exists and is not marked as Onyx-generated", filename)
}

func ensureNoJekyll(root string) error {
	filename := filepath.Join(root, ".nojekyll")
	if _, err := os.Stat(filename); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(filename, []byte("Generated by Onyx so GitHub Pages serves static files without Jekyll.\n"), 0o644)
}

func isBlankFile(data []byte) bool {
	if len(bytes.TrimSpace(data)) == 0 {
		return true
	}
	if bytes.HasPrefix(data, []byte{0xff, 0xfe}) {
		for _, b := range data[2:] {
			if b != 0 && b != '\r' && b != '\n' && b != '\t' && b != ' ' {
				return false
			}
		}
		return true
	}
	return false
}

func preparePublic(publicDir string) error {
	info, err := os.Stat(publicDir)
	if err == nil {
		if !info.IsDir() {
			return fmt.Errorf("%s exists and is not a directory", publicDir)
		}
		if _, err := os.Stat(filepath.Join(publicDir, publicMarker)); err != nil {
			return fmt.Errorf("%s exists but is missing %s; refusing to overwrite", publicDir, publicMarker)
		}
		if err := os.RemoveAll(publicDir); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	if err := os.MkdirAll(publicDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(publicDir, publicMarker), []byte("generated by Onyx\n"), 0o644)
}
