package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"html/template"
	"io"
	"io/fs"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

const generatedMarker = "<!-- generated by Onyx; do not edit -->"
const publicMarker = ".onyx-generated"

// defaultSources are the conventional content folders Onyx looks for when no
// explicit source is configured. Every one that exists is included in the
// build: one folder builds as-is, several build a sectioned site.
var defaultSources = []string{"doc", "docs", "plan", "plans", "wiki"}

type Config struct {
	Root       string
	ConfigPath string
	SiteTitle  string
	Sources    []string
	Multi      bool
	Theme      string
	Search     bool
	Graph      bool
	ShowSource bool
}

// sourcePrefix is the path segment prepended when turning an in-vault relative
// path into a real, root-relative one (for Markdown-source links and assets).
// With a single source every page path is relative to that folder, so the
// folder name is the prefix. With several sources page paths are already
// root-relative (they carry their own folder), so the prefix is empty.
func (c Config) sourcePrefix() string {
	if c.Multi || len(c.Sources) == 0 {
		return ""
	}
	return c.Sources[0]
}

type Vault struct {
	Config       Config
	Notes        []*Page
	Home         *Page
	ByPath       map[string]*Page
	ByBase       map[string][]*Page
	AssetsByPath map[string]string
	AssetsByBase map[string][]string
}

type Page struct {
	SourceRel   string
	SourceAbs   string
	PageRel     string
	URL         string
	SourceURL   string
	Title       string
	Body        string
	HTML        template.HTML
	Text        string
	Excerpt     string
	Headings    []string
	Tags        []string
	Outgoing    map[string]bool
	Backlinks   []LinkView
	FrontMatter map[string]string
	IsHome      bool
	Generated   bool
	HasMath     bool
}

type LinkView struct {
	Title string `json:"title"`
	URL   string `json:"url"`
	Path  string `json:"path"`
}

type SearchItem struct {
	Title    string   `json:"title"`
	URL      string   `json:"url"`
	Path     string   `json:"path"`
	Excerpt  string   `json:"excerpt"`
	Headings []string `json:"headings,omitempty"`
	Tags     []string `json:"tags,omitempty"`
}

type GraphNode struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	URL    string `json:"url"`
	Degree int    `json:"degree"`
}

type GraphLink struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

type GraphData struct {
	Nodes []GraphNode `json:"nodes"`
	Links []GraphLink `json:"links"`
}

type TemplateData struct {
	Site       SiteView
	Page       *Page
	Nav        template.HTML
	Backlinks  []LinkView
	Search     bool
	Graph      bool
	ShowSource bool
	Generated  template.HTML
	RootScript template.JS
	PageID     template.JS
	HomeURL    string
	CSSURL     string
	JSURL      string
}

type SiteView struct {
	Title string
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout, stderr io.Writer) int {
	if err := runErr(args, stdout, stderr); err != nil {
		fmt.Fprintf(stderr, "onyx: %v\n", err)
		return 1
	}
	return 0
}

func runErr(args []string, stdout, stderr io.Writer) error {
	if len(args) > 1 {
		return errors.New("usage: onyx [site-root-or-child]")
	}

	start := "."
	if len(args) == 1 {
		start = args[0]
	}

	root, configPath, err := findConfig(start)
	if err != nil {
		return err
	}

	cfg, err := readConfig(root, configPath)
	if err != nil {
		return err
	}

	warnings, err := buildSite(cfg)
	if err != nil {
		return err
	}
	for _, warning := range warnings {
		fmt.Fprintf(stderr, "warning: %s\n", warning)
	}
	fmt.Fprintf(stdout, "Onyx built %d pages into %s\n", countPages(cfg.Root), filepath.Join(cfg.Root, "public"))
	return nil
}

func countPages(root string) int {
	count := 0
	_ = filepath.WalkDir(filepath.Join(root, "public"), func(p string, d fs.DirEntry, err error) error {
		if err == nil && !d.IsDir() && d.Name() == "index.html" {
			count++
		}
		return nil
	})
	if _, err := os.Stat(filepath.Join(root, "index.html")); err == nil {
		count++
	}
	return count
}

func findConfig(start string) (string, string, error) {
	abs, err := filepath.Abs(start)
	if err != nil {
		return "", "", err
	}
	info, err := os.Stat(abs)
	if err != nil {
		return "", "", err
	}
	if !info.IsDir() {
		abs = filepath.Dir(abs)
	}

	for {
		ini := filepath.Join(abs, "onyx.ini")
		if _, err := os.Stat(ini); err == nil {
			return abs, ini, nil
		}
		if hasDefaultSource(abs) {
			// No onyx.ini, but a conventional source folder (docs/, wiki/, ...)
			// marks the site root. The returned path is where an optional
			// onyx.ini would live; readConfig tolerates its absence.
			return abs, ini, nil
		}
		parent := filepath.Dir(abs)
		if parent == abs {
			return "", "", errors.New("no onyx.ini or content directory (doc/, docs/, plan/, plans/, wiki/) found in this directory or its parents")
		}
		abs = parent
	}
}

func hasDefaultSource(dir string) bool {
	for _, name := range defaultSources {
		if info, err := os.Stat(filepath.Join(dir, name)); err == nil && info.IsDir() {
			return true
		}
	}
	return false
}

func readConfig(root, configPath string) (Config, error) {
	// onyx.ini is optional: a missing file leaves every setting at its default.
	values := map[string]string{}
	if configPath != "" {
		parsed, err := parseINI(configPath)
		if err != nil && !os.IsNotExist(err) {
			return Config{}, err
		}
		if parsed != nil {
			values = parsed
		}
	}

	sources, err := resolveSources(root, values)
	if err != nil {
		return Config{}, err
	}

	cfg := Config{
		Root:       root,
		ConfigPath: configPath,
		// An empty title is a sentinel: loadVault later falls back to the home
		// page's title and finally to "Onyx".
		SiteTitle:  valueOr(values, "site_title", ""),
		Sources:    sources,
		Multi:      len(sources) > 1,
		Theme:      valueOr(values, "theme", "theme"),
		Search:     boolOr(values, true, "search", "build.search"),
		Graph:      boolOr(values, true, "graph", "build.graph"),
		ShowSource: boolOr(values, true, "show_source", "publish_raw_markdown"),
	}

	if filepath.IsAbs(cfg.Theme) {
		return Config{}, errors.New("theme must be relative to the site root")
	}

	return cfg, nil
}

// resolveSources determines which content folders to build. An explicit
// source = a, b, c in onyx.ini wins and every listed folder must exist;
// otherwise Onyx auto-detects which of the default folders are present and
// includes all of them.
func resolveSources(root string, values map[string]string) ([]string, error) {
	requested := defaultSources
	explicit := false
	if raw, ok := values["source"]; ok && strings.TrimSpace(raw) != "" {
		requested = splitList(raw)
		explicit = true
	}

	var sources []string
	for _, name := range requested {
		if filepath.IsAbs(name) {
			return nil, errors.New("source must be relative to the site root")
		}
		dir := filepath.Join(root, filepath.FromSlash(name))
		info, err := os.Stat(dir)
		if err != nil {
			if explicit {
				return nil, fmt.Errorf("source directory %q: %w", name, err)
			}
			continue // an auto-detected default that simply isn't present
		}
		if !info.IsDir() {
			if explicit {
				return nil, fmt.Errorf("source %q is not a directory", name)
			}
			continue
		}
		sources = append(sources, path.Clean(filepath.ToSlash(name)))
	}

	if len(sources) == 0 {
		if explicit {
			return nil, errors.New("none of the configured source directories exist")
		}
		return nil, fmt.Errorf("no content directory found (looked for %s)", strings.Join(defaultSources, ", "))
	}
	return sources, nil
}

// splitList parses a comma- or whitespace-separated value into a deduplicated,
// order-preserving list.
func splitList(raw string) []string {
	fields := strings.FieldsFunc(raw, func(r rune) bool {
		return r == ',' || unicode.IsSpace(r)
	})
	seen := map[string]bool{}
	out := make([]string, 0, len(fields))
	for _, f := range fields {
		if f == "" || seen[f] {
			continue
		}
		seen[f] = true
		out = append(out, f)
	}
	return out
}

func parseINI(filename string) (map[string]string, error) {
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}
	text := strings.ReplaceAll(string(bytes.TrimPrefix(data, []byte("\xef\xbb\xbf"))), "\r\n", "\n")
	values := map[string]string{}
	section := ""

	for lineNo, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section = strings.ToLower(strings.TrimSpace(line[1 : len(line)-1]))
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("%s:%d: expected key = value", filename, lineNo+1)
		}
		key = strings.ToLower(strings.TrimSpace(key))
		val = stripQuotes(strings.TrimSpace(stripInlineComment(val)))
		if section != "" {
			values[section+"."+key] = val
		}
		values[key] = val
	}

	return values, nil
}

func stripInlineComment(s string) string {
	inQuote := rune(0)
	for i, r := range s {
		if r == '\'' || r == '"' {
			if inQuote == 0 {
				inQuote = r
			} else if inQuote == r {
				inQuote = 0
			}
			continue
		}
		if inQuote == 0 && (r == '#' || r == ';') {
			if i == 0 || unicode.IsSpace(rune(s[i-1])) {
				return strings.TrimSpace(s[:i])
			}
		}
	}
	return s
}

func stripQuotes(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func valueOr(values map[string]string, key, fallback string) string {
	if v, ok := values[key]; ok && strings.TrimSpace(v) != "" {
		return strings.TrimSpace(v)
	}
	return fallback
}

func boolOr(values map[string]string, fallback bool, keys ...string) bool {
	for _, key := range keys {
		if raw, ok := values[key]; ok {
			switch strings.ToLower(strings.TrimSpace(raw)) {
			case "1", "true", "yes", "on":
				return true
			case "0", "false", "no", "off":
				return false
			}
		}
	}
	return fallback
}

func buildSite(cfg Config) ([]string, error) {
	if err := ensureRootIndexWritable(filepath.Join(cfg.Root, "index.html")); err != nil {
		return nil, err
	}
	if err := ensureNoJekyll(cfg.Root); err != nil {
		return nil, err
	}

	vault, warnings, err := loadVault(cfg)
	if err != nil {
		return warnings, err
	}
	renderVault(vault, &warnings)
	computeBacklinks(vault)

	if err := preparePublic(filepath.Join(cfg.Root, "public")); err != nil {
		return warnings, err
	}
	if err := writeAssets(vault); err != nil {
		return warnings, err
	}
	if err := writePages(vault); err != nil {
		return warnings, err
	}
	if cfg.Search {
		if err := writeSearchIndex(vault); err != nil {
			return warnings, err
		}
	}
	if cfg.Graph {
		if err := writeGraph(vault); err != nil {
			return warnings, err
		}
	}

	return warnings, nil
}

func ensureRootIndexWritable(filename string) error {
	data, err := os.ReadFile(filename)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if bytes.Contains(data, []byte(generatedMarker)) ||
		bytes.Contains(data, []byte(html.EscapeString(generatedMarker))) ||
		isBlankFile(data) {
		return nil
	}
	return fmt.Errorf("%s exists and is not marked as Onyx-generated", filename)
}

func ensureNoJekyll(root string) error {
	filename := filepath.Join(root, ".nojekyll")
	if _, err := os.Stat(filename); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(filename, []byte("Generated by Onyx so GitHub Pages serves static files without Jekyll.\n"), 0o644)
}

func isBlankFile(data []byte) bool {
	if len(bytes.TrimSpace(data)) == 0 {
		return true
	}
	if bytes.HasPrefix(data, []byte{0xff, 0xfe}) {
		for _, b := range data[2:] {
			if b != 0 && b != '\r' && b != '\n' && b != '\t' && b != ' ' {
				return false
			}
		}
		return true
	}
	return false
}

func preparePublic(publicDir string) error {
	info, err := os.Stat(publicDir)
	if err == nil {
		if !info.IsDir() {
			return fmt.Errorf("%s exists and is not a directory", publicDir)
		}
		if _, err := os.Stat(filepath.Join(publicDir, publicMarker)); err != nil {
			return fmt.Errorf("%s exists but is missing %s; refusing to overwrite", publicDir, publicMarker)
		}
		if err := os.RemoveAll(publicDir); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		return err
	}

	if err := os.MkdirAll(publicDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(publicDir, publicMarker), []byte("generated by Onyx\n"), 0o644)
}

func loadVault(cfg Config) (*Vault, []string, error) {
	vault := &Vault{
		Config:       cfg,
		ByPath:       map[string]*Page{},
		ByBase:       map[string][]*Page{},
		AssetsByPath: map[string]string{},
		AssetsByBase: map[string][]string{},
	}
	var warnings []string

	for _, src := range cfg.Sources {
		sourceDir := filepath.Join(cfg.Root, filepath.FromSlash(src))
		// With a single source, paths are relative to that folder (it builds
		// as-is). With several, they are relative to the site root, so each
		// note carries its source folder as a section prefix.
		relBase := sourceDir
		if cfg.Multi {
			relBase = cfg.Root
		}

		err := filepath.WalkDir(sourceDir, func(abs string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if abs == sourceDir {
				return nil
			}
			if shouldSkipName(d.Name()) {
				if d.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}

			relOS, err := filepath.Rel(relBase, abs)
			if err != nil {
				return err
			}
			rel := filepath.ToSlash(relOS)
			if hasSkippedComponent(rel) {
				if d.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
			if d.IsDir() {
				return nil
			}

			if strings.EqualFold(filepath.Ext(d.Name()), ".md") {
				page, excluded, err := readPage(abs, rel)
				if err != nil {
					return err
				}
				if excluded {
					warnings = append(warnings, rel+": excluded by frontmatter")
					return nil
				}
				vault.Notes = append(vault.Notes, page)
				return nil
			}

			vault.addAsset(rel)
			return nil
		})
		if err != nil {
			return nil, warnings, err
		}
	}

	sort.Slice(vault.Notes, func(i, j int) bool {
		return strings.ToLower(vault.Notes[i].SourceRel) < strings.ToLower(vault.Notes[j].SourceRel)
	})

	for _, note := range vault.Notes {
		note.PageRel = strings.TrimSuffix(note.SourceRel, path.Ext(note.SourceRel))
		vault.ByPath[strings.ToLower(note.PageRel)] = note
		base := strings.ToLower(path.Base(note.PageRel))
		vault.ByBase[base] = append(vault.ByBase[base], note)
	}

	for _, list := range vault.ByBase {
		sort.Slice(list, func(i, j int) bool {
			return strings.ToLower(list[i].SourceRel) < strings.ToLower(list[j].SourceRel)
		})
	}

	vault.Home = chooseHome(vault)
	// Resolve the site title before any generated home is built (generatedHome
	// reads it): an explicit onyx.ini title wins, else the home page's title,
	// else "Onyx".
	if vault.Config.SiteTitle == "" {
		if vault.Home != nil {
			vault.Config.SiteTitle = vault.Home.Title
		} else {
			vault.Config.SiteTitle = "Onyx"
		}
	}
	if vault.Home == nil {
		vault.Home = generatedHome(vault)
		vault.Notes = append([]*Page{vault.Home}, vault.Notes...)
	}
	vault.Home.IsHome = true

	for _, note := range vault.Notes {
		if note.IsHome {
			note.URL = ""
		} else {
			note.URL = "public/" + escapeURLPath(note.PageRel) + "/"
		}
		if note.SourceRel != "" {
			note.SourceURL = escapeURLPath(path.Join(cfg.sourcePrefix(), note.SourceRel))
		}
	}
	if vault.Home.Generated {
		updateGeneratedHome(vault)
	}

	return vault, warnings, nil
}

func shouldSkipName(name string) bool {
	if strings.HasPrefix(name, ".") {
		return true
	}
	switch strings.ToLower(name) {
	case ".obsidian", ".git", ".trash":
		return true
	}
	return false
}

func hasSkippedComponent(rel string) bool {
	for _, part := range strings.Split(rel, "/") {
		if shouldSkipName(part) {
			return true
		}
	}
	return false
}

func readPage(abs, rel string) (*Page, bool, error) {
	data, err := os.ReadFile(abs)
	if err != nil {
		return nil, false, err
	}
	text := normalizeNewlines(stripUTF8BOM(string(data)))
	frontMatter, body := splitFrontMatter(text)

	if strings.EqualFold(frontMatter["publish"], "false") || truthy(frontMatter["draft"]) {
		return nil, true, nil
	}

	title := strings.TrimSpace(frontMatter["title"])
	if title == "" {
		title = firstHeading(body)
	}
	if title == "" {
		title = strings.TrimSuffix(path.Base(rel), path.Ext(rel))
	}

	return &Page{
		SourceRel:   rel,
		SourceAbs:   abs,
		Title:       title,
		Body:        body,
		FrontMatter: frontMatter,
		Outgoing:    map[string]bool{},
	}, false, nil
}

func stripUTF8BOM(s string) string {
	return strings.TrimPrefix(s, "\ufeff")
}

func normalizeNewlines(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	return strings.ReplaceAll(s, "\r", "\n")
}

func splitFrontMatter(text string) (map[string]string, string) {
	frontMatter := map[string]string{}
	if !strings.HasPrefix(text, "---\n") {
		return frontMatter, text
	}

	lines := strings.Split(text, "\n")
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "---" {
			for _, line := range lines[1:i] {
				key, value, ok := strings.Cut(line, ":")
				if !ok {
					continue
				}
				frontMatter[strings.ToLower(strings.TrimSpace(key))] = stripQuotes(strings.TrimSpace(value))
			}
			return frontMatter, strings.Join(lines[i+1:], "\n")
		}
	}
	return map[string]string{}, text
}

func truthy(s string) bool {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func firstHeading(body string) string {
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if level, text, ok := heading(trimmed); ok && level == 1 {
			return stripInlineMarkdown(text)
		}
	}
	return ""
}

func chooseHome(vault *Vault) *Page {
	if page := vault.ByPath["index"]; page != nil {
		return page
	}
	if page := vault.ByPath["home"]; page != nil {
		return page
	}
	return nil
}

func generatedHome(vault *Vault) *Page {
	return &Page{
		Title:     vault.Config.SiteTitle,
		Text:      vault.Config.SiteTitle,
		Excerpt:   "Generated index",
		Outgoing:  map[string]bool{},
		IsHome:    true,
		Generated: true,
	}
}

func updateGeneratedHome(vault *Vault) {
	if vault.Config.Multi {
		updateSectionedHome(vault)
		return
	}

	var b strings.Builder
	b.WriteString("<p>This site was generated from a folder of Markdown notes.</p>\n")
	b.WriteString("<ul>\n")
	for _, note := range vault.Notes {
		if note.Generated {
			continue
		}
		b.WriteString(`<li><a href="`)
		b.WriteString(html.EscapeString(relativeURL(vault.Home, note.URL)))
		b.WriteString(`">`)
		b.WriteString(html.EscapeString(note.Title))
		b.WriteString("</a></li>\n")
	}
	b.WriteString("</ul>\n")
	vault.Home.HTML = template.HTML(b.String())
}

// updateSectionedHome renders the multi-source landing page: one section per
// source folder, each listing its notes. The left-hand nav already nests the
// same folders, so the two stay in step.
func updateSectionedHome(vault *Vault) {
	var b strings.Builder
	b.WriteString("<p>This site collects several sets of notes. Choose a section to start.</p>\n")
	for _, src := range vault.Config.Sources {
		section := strings.ToLower(path.Clean(filepath.ToSlash(src))) + "/"
		var items []*Page
		for _, note := range vault.Notes {
			if note.Generated {
				continue
			}
			if strings.HasPrefix(strings.ToLower(note.PageRel)+"/", section) {
				items = append(items, note)
			}
		}
		if len(items) == 0 {
			continue
		}
		b.WriteString(`<section class="onyx-index-section">` + "\n")
		b.WriteString("<h2>")
		b.WriteString(html.EscapeString(titleCase(path.Base(path.Clean(filepath.ToSlash(src))))))
		b.WriteString("</h2>\n<ul>\n")
		for _, note := range items {
			b.WriteString(`<li><a href="`)
			b.WriteString(html.EscapeString(relativeURL(vault.Home, note.URL)))
			b.WriteString(`">`)
			b.WriteString(html.EscapeString(note.Title))
			b.WriteString("</a></li>\n")
		}
		b.WriteString("</ul>\n</section>\n")
	}
	vault.Home.HTML = template.HTML(b.String())
}

func (v *Vault) addAsset(rel string) {
	key := strings.ToLower(strings.TrimPrefix(path.Clean(rel), "./"))
	v.AssetsByPath[key] = rel
	base := strings.ToLower(path.Base(rel))
	v.AssetsByBase[base] = append(v.AssetsByBase[base], rel)
}

func renderVault(vault *Vault, warnings *[]string) {
	for _, note := range vault.Notes {
		if note.Generated {
			continue
		}
		renderer := &MarkdownRenderer{
			vault:      vault,
			current:    note,
			warnings:   warnings,
			headingIDs: map[string]int{},
			outgoing:   map[string]bool{},
		}
		result := renderer.Render(note.Body)
		note.HTML = template.HTML(result.HTML)
		note.Text = result.Text
		note.Excerpt = excerpt(result.Text, 220)
		note.Headings = result.Headings
		note.Tags = result.Tags
		note.HasMath = result.HasMath
		note.Outgoing = renderer.outgoing
	}
}

func computeBacklinks(vault *Vault) {
	byRel := map[string]*Page{}
	for _, note := range vault.Notes {
		if !note.Generated {
			byRel[note.PageRel] = note
		}
	}
	for _, note := range vault.Notes {
		for target := range note.Outgoing {
			if page := byRel[target]; page != nil && page != note {
				page.Backlinks = append(page.Backlinks, LinkView{
					Title: note.Title,
					URL:   note.URL,
					Path:  note.SourceRel,
				})
			}
		}
	}
	for _, note := range vault.Notes {
		sort.Slice(note.Backlinks, func(i, j int) bool {
			return strings.ToLower(note.Backlinks[i].Title) < strings.ToLower(note.Backlinks[j].Title)
		})
	}
}

func writeAssets(vault *Vault) error {
	publicDir := filepath.Join(vault.Config.Root, "public")
	themeDir := filepath.Join(vault.Config.Root, filepath.FromSlash(vault.Config.Theme))

	if err := writeThemeOrDefault(filepath.Join(themeDir, "style.css"), filepath.Join(publicDir, "onyx.css"), defaultCSS); err != nil {
		return err
	}
	if err := writeThemeOrDefault(filepath.Join(themeDir, "onyx.js"), filepath.Join(publicDir, "onyx.js"), defaultJS); err != nil {
		return err
	}

	staticDir := filepath.Join(themeDir, "static")
	if info, err := os.Stat(staticDir); err == nil && info.IsDir() {
		return copyDir(staticDir, filepath.Join(publicDir, "theme"))
	}
	return nil
}

func writeThemeOrDefault(source, dest, fallback string) error {
	if data, err := os.ReadFile(source); err == nil {
		return os.WriteFile(dest, data, 0o644)
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(dest, []byte(fallback), 0o644)
}

func copyDir(source, dest string) error {
	return filepath.WalkDir(source, func(abs string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if abs == source {
			return nil
		}
		if shouldSkipName(d.Name()) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(source, abs)
		if err != nil {
			return err
		}
		out := filepath.Join(dest, rel)
		if d.IsDir() {
			return os.MkdirAll(out, 0o755)
		}
		data, err := os.ReadFile(abs)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
			return err
		}
		return os.WriteFile(out, data, 0o644)
	})
}

func writePages(vault *Vault) error {
	pageTemplate, err := loadTemplateSource(vault, "page.html", defaultPageTemplate)
	if err != nil {
		return err
	}
	homeTemplate, err := loadTemplateSource(vault, "home.html", defaultPageTemplate)
	if err != nil {
		return err
	}

	for _, page := range vault.Notes {
		tpl := pageTemplate
		if page.IsHome {
			tpl = homeTemplate
		}
		if err := writePage(vault, page, tpl); err != nil {
			return err
		}
	}
	return nil
}

type templateSource struct {
	name   string
	source string
}

func loadTemplateSource(vault *Vault, name, fallback string) (templateSource, error) {
	themePath := filepath.Join(vault.Config.Root, filepath.FromSlash(vault.Config.Theme), name)
	source := fallback
	if data, err := os.ReadFile(themePath); err == nil {
		source = string(data)
	} else if !os.IsNotExist(err) {
		return templateSource{}, err
	}
	return templateSource{name: name, source: source}, nil
}

func parseTemplateForPage(vault *Vault, page *Page, source templateSource) (*template.Template, error) {
	funcs := template.FuncMap{
		"asset": func(name string) string {
			return relativeURL(page, "public/"+escapeURLPath(name))
		},
	}
	return template.New(source.name).Funcs(funcs).Parse(source.source)
}

func writePage(vault *Vault, page *Page, source templateSource) error {
	tpl, err := parseTemplateForPage(vault, page, source)
	if err != nil {
		return err
	}
	pageView := *page
	pageView.URL = relativeURL(page, page.URL)
	if page.SourceURL != "" {
		pageView.SourceURL = relativeURL(page, page.SourceURL)
	}
	data := TemplateData{
		Site: SiteView{
			Title: vault.Config.SiteTitle,
		},
		Page:       &pageView,
		Nav:        template.HTML(renderNav(vault, page)),
		Backlinks:  relativeLinkViews(page, page.Backlinks),
		Search:     vault.Config.Search,
		Graph:      vault.Config.Graph,
		ShowSource: vault.Config.ShowSource && page.SourceURL != "",
		Generated:  template.HTML(generatedMarker),
		RootScript: template.JS(strconv.Quote(relativeRoot(page))),
		PageID:     template.JS(strconv.Quote(page.PageRel)),
		HomeURL:    relativeURL(page, ""),
		CSSURL:     relativeURL(page, "public/onyx.css"),
		JSURL:      relativeURL(page, "public/onyx.js"),
	}

	var out bytes.Buffer
	if err := tpl.Execute(&out, data); err != nil {
		return err
	}

	if page.IsHome {
		return os.WriteFile(filepath.Join(vault.Config.Root, "index.html"), out.Bytes(), 0o644)
	}

	dest := filepath.Join(vault.Config.Root, "public", filepath.FromSlash(page.PageRel), "index.html")
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dest, out.Bytes(), 0o644)
}

func relativeLinkViews(from *Page, links []LinkView) []LinkView {
	out := make([]LinkView, 0, len(links))
	for _, link := range links {
		link.URL = relativeURL(from, link.URL)
		out = append(out, link)
	}
	return out
}

func writeSearchIndex(vault *Vault) error {
	items := make([]SearchItem, 0, len(vault.Notes))
	for _, page := range vault.Notes {
		items = append(items, SearchItem{
			Title:    page.Title,
			URL:      page.URL,
			Path:     page.SourceRel,
			Excerpt:  page.Excerpt,
			Headings: page.Headings,
			Tags:     page.Tags,
		})
	}
	data, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(filepath.Join(vault.Config.Root, "public", "search-index.json"), data, 0o644)
}

// writeGraph emits public/graph.json: one node per published note and one link
// per resolved outgoing wikilink, so the browser can draw the knowledge graph.
func writeGraph(vault *Vault) error {
	indexByRel := map[string]int{}
	nodes := make([]GraphNode, 0, len(vault.Notes))
	for _, page := range vault.Notes {
		if page.Generated {
			continue
		}
		indexByRel[page.PageRel] = len(nodes)
		nodes = append(nodes, GraphNode{
			ID:    page.PageRel,
			Title: page.Title,
			URL:   page.URL,
		})
	}

	links := make([]GraphLink, 0)
	seen := map[string]bool{}
	for _, page := range vault.Notes {
		srcIdx, ok := indexByRel[page.PageRel]
		if !ok {
			continue
		}
		targets := make([]string, 0, len(page.Outgoing))
		for target := range page.Outgoing {
			targets = append(targets, target)
		}
		sort.Strings(targets)
		for _, target := range targets {
			tgtIdx, ok := indexByRel[target]
			if !ok || target == page.PageRel {
				continue
			}
			key := page.PageRel + "\x00" + target
			if seen[key] {
				continue
			}
			seen[key] = true
			links = append(links, GraphLink{Source: page.PageRel, Target: target})
			nodes[srcIdx].Degree++
			nodes[tgtIdx].Degree++
		}
	}

	data, err := json.MarshalIndent(GraphData{Nodes: nodes, Links: links}, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(filepath.Join(vault.Config.Root, "public", "graph.json"), data, 0o644)
}

type NavNode struct {
	Name     string
	Path     string
	Page     *Page
	Children map[string]*NavNode
}

func renderNav(vault *Vault, current *Page) string {
	root := &NavNode{Children: map[string]*NavNode{}}
	for _, page := range vault.Notes {
		if page.IsHome {
			continue
		}
		insertNav(root, page)
	}

	var b strings.Builder
	b.WriteString(`<ul class="nav-tree">`)
	b.WriteString(`<li><a`)
	if current.IsHome {
		b.WriteString(` aria-current="page"`)
	}
	b.WriteString(` href="`)
	b.WriteString(html.EscapeString(relativeURL(current, "")))
	b.WriteString(`">Home</a></li>`)
	writeNavChildren(&b, root, current)
	b.WriteString(`</ul>`)
	return b.String()
}

func insertNav(root *NavNode, page *Page) {
	segments := strings.Split(page.PageRel, "/")
	node := root
	prefix := ""
	for _, segment := range segments {
		key := strings.ToLower(segment)
		if prefix == "" {
			prefix = key
		} else {
			prefix += "/" + key
		}
		if node.Children == nil {
			node.Children = map[string]*NavNode{}
		}
		child := node.Children[key]
		if child == nil {
			child = &NavNode{Name: segment, Path: prefix, Children: map[string]*NavNode{}}
			node.Children[key] = child
		}
		node = child
	}
	node.Page = page
	node.Name = page.Title
}

func writeNavChildren(b *strings.Builder, node *NavNode, current *Page) {
	children := make([]*NavNode, 0, len(node.Children))
	for _, child := range node.Children {
		children = append(children, child)
	}
	sort.Slice(children, func(i, j int) bool {
		iFolder := len(children[i].Children) > 0
		jFolder := len(children[j].Children) > 0
		if iFolder != jFolder {
			return iFolder
		}
		return strings.ToLower(children[i].Name) < strings.ToLower(children[j].Name)
	})

	currentPath := strings.ToLower(current.PageRel)
	for _, child := range children {
		b.WriteString("<li>")
		if len(child.Children) > 0 {
			onPath := currentPath == child.Path || strings.HasPrefix(currentPath, child.Path+"/")
			b.WriteString("<details")
			if onPath {
				b.WriteString(" open")
			}
			b.WriteString("><summary>")
			writeNavLabel(b, child, current)
			b.WriteString("</summary><ul>")
			writeNavChildren(b, child, current)
			b.WriteString("</ul></details>")
		} else {
			writeNavLabel(b, child, current)
		}
		b.WriteString("</li>")
	}
}

func writeNavLabel(b *strings.Builder, node *NavNode, current *Page) {
	if node.Page == nil {
		b.WriteString(`<span>`)
		b.WriteString(html.EscapeString(node.Name))
		b.WriteString(`</span>`)
		return
	}
	b.WriteString(`<a`)
	if node.Page == current {
		b.WriteString(` aria-current="page"`)
	}
	b.WriteString(` href="`)
	b.WriteString(html.EscapeString(relativeURL(current, node.Page.URL)))
	b.WriteString(`">`)
	b.WriteString(html.EscapeString(node.Name))
	b.WriteString(`</a>`)
}

type MarkdownRenderer struct {
	vault      *Vault
	current    *Page
	warnings   *[]string
	headingIDs map[string]int
	outgoing   map[string]bool
	headings   []string
	hasMath    bool
}

type RenderResult struct {
	HTML     string
	Text     string
	Headings []string
	Tags     []string
	HasMath  bool
}

func (r *MarkdownRenderer) Render(markdown string) RenderResult {
	markdown = normalizeNewlines(markdown)
	htmlOut := r.renderBlocks(strings.Split(markdown, "\n"))
	text := plainText(markdown)
	return RenderResult{
		HTML:     htmlOut,
		Text:     text,
		Headings: r.headings,
		Tags:     extractTags(markdown),
		HasMath:  r.hasMath,
	}
}

func (r *MarkdownRenderer) renderBlocks(lines []string) string {
	var b strings.Builder
	for i := 0; i < len(lines); {
		line := lines[i]
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			i++
			continue
		}

		if fence, info, ok := fenceStart(trimmed); ok {
			j := i + 1
			var code []string
			for ; j < len(lines); j++ {
				if strings.HasPrefix(strings.TrimSpace(lines[j]), fence) {
					break
				}
				code = append(code, lines[j])
			}
			class := ""
			if info != "" {
				class = ` class="language-` + html.EscapeString(sanitizeClass(info)) + `"`
			}
			b.WriteString("<pre><code")
			b.WriteString(class)
			b.WriteString(">")
			b.WriteString(html.EscapeString(strings.Join(code, "\n")))
			b.WriteString("</code></pre>\n")
			if j < len(lines) {
				i = j + 1
			} else {
				i = j
			}
			continue
		}

		if mathLines, next, ok := mathBlock(lines, i); ok {
			r.hasMath = true
			b.WriteString(`<div class="onyx-math">`)
			b.WriteString("$$\n")
			b.WriteString(html.EscapeString(strings.Join(mathLines, "\n")))
			b.WriteString("\n$$")
			b.WriteString("</div>\n")
			i = next
			continue
		}

		if isTableStart(lines, i) {
			j := i + 2
			for j < len(lines) && strings.Contains(lines[j], "|") && strings.TrimSpace(lines[j]) != "" {
				j++
			}
			b.WriteString(r.renderTable(lines[i:j]))
			i = j
			continue
		}

		if level, text, ok := heading(trimmed); ok {
			title := stripInlineMarkdown(text)
			id := r.uniqueHeadingID(slugify(title))
			r.headings = append(r.headings, title)
			fmt.Fprintf(&b, `<h%d id="%s">%s</h%d>`+"\n", level, html.EscapeString(id), r.renderInline(text), level)
			i++
			continue
		}

		if isHorizontalRule(trimmed) {
			b.WriteString("<hr>\n")
			i++
			continue
		}

		if strings.HasPrefix(strings.TrimLeft(line, " "), ">") {
			j := i
			var quote []string
			for j < len(lines) {
				if strings.TrimSpace(lines[j]) == "" {
					quote = append(quote, "")
					j++
					continue
				}
				if !strings.HasPrefix(strings.TrimLeft(lines[j], " "), ">") {
					break
				}
				quote = append(quote, stripBlockquoteMarker(lines[j]))
				j++
			}
			b.WriteString(r.renderBlockquote(quote))
			i = j
			continue
		}

		if ordered, _, ok := listMarker(line); ok {
			tag := "ul"
			if ordered {
				tag = "ol"
			}
			b.WriteString("<" + tag + ">\n")
			j := i
			for j < len(lines) {
				nextOrdered, nextContent, ok := listMarker(lines[j])
				if !ok || nextOrdered != ordered {
					break
				}
				b.WriteString("<li>")
				b.WriteString(r.renderListItem(nextContent))
				b.WriteString("</li>\n")
				j++
			}
			b.WriteString("</" + tag + ">\n")
			i = j
			continue
		}

		j := i
		var para []string
		for j < len(lines) {
			if strings.TrimSpace(lines[j]) == "" || startsBlock(lines, j) {
				break
			}
			para = append(para, strings.TrimSpace(lines[j]))
			j++
		}
		b.WriteString("<p>")
		b.WriteString(r.renderInline(strings.Join(para, " ")))
		b.WriteString("</p>\n")
		i = j
	}
	return b.String()
}

func fenceStart(line string) (string, string, bool) {
	if strings.HasPrefix(line, "```") {
		return "```", strings.TrimSpace(line[3:]), true
	}
	if strings.HasPrefix(line, "~~~") {
		return "~~~", strings.TrimSpace(line[3:]), true
	}
	return "", "", false
}

func sanitizeClass(s string) string {
	fields := strings.Fields(s)
	if len(fields) == 0 {
		return ""
	}
	s = fields[0]
	var b strings.Builder
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '-' || r == '_' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func startsBlock(lines []string, i int) bool {
	trimmed := strings.TrimSpace(lines[i])
	if trimmed == "" {
		return true
	}
	if _, _, ok := fenceStart(trimmed); ok {
		return true
	}
	if _, _, ok := heading(trimmed); ok {
		return true
	}
	if isHorizontalRule(trimmed) {
		return true
	}
	if strings.HasPrefix(strings.TrimLeft(lines[i], " "), ">") {
		return true
	}
	if _, _, ok := listMarker(lines[i]); ok {
		return true
	}
	if strings.HasPrefix(trimmed, "$$") {
		return true
	}
	return isTableStart(lines, i)
}

func heading(line string) (int, string, bool) {
	count := 0
	for count < len(line) && line[count] == '#' {
		count++
	}
	if count == 0 || count > 6 || count >= len(line) || line[count] != ' ' {
		return 0, "", false
	}
	return count, strings.TrimSpace(line[count+1:]), true
}

func isHorizontalRule(line string) bool {
	if len(line) < 3 {
		return false
	}
	for _, marker := range []rune{'-', '*', '_'} {
		count := 0
		ok := true
		for _, r := range line {
			if unicode.IsSpace(r) {
				continue
			}
			if r != marker {
				ok = false
				break
			}
			count++
		}
		if ok && count >= 3 {
			return true
		}
	}
	return false
}

func stripBlockquoteMarker(line string) string {
	line = strings.TrimLeft(line, " ")
	if strings.HasPrefix(line, ">") {
		line = line[1:]
	}
	return strings.TrimPrefix(line, " ")
}

func (r *MarkdownRenderer) renderBlockquote(lines []string) string {
	first := ""
	for _, line := range lines {
		if strings.TrimSpace(line) != "" {
			first = strings.TrimSpace(line)
			break
		}
	}

	if strings.HasPrefix(first, "[!") {
		end := strings.Index(first, "]")
		if end > 2 {
			kind := strings.ToLower(strings.TrimSpace(first[2:end]))
			title := strings.TrimSpace(first[end+1:])
			if title == "" {
				title = titleCase(kind)
			}
			body := dropFirstNonBlank(lines)
			var b strings.Builder
			b.WriteString(`<aside class="callout callout-`)
			b.WriteString(html.EscapeString(sanitizeClass(kind)))
			b.WriteString(`"><p class="callout-title">`)
			b.WriteString(html.EscapeString(title))
			b.WriteString("</p>\n")
			b.WriteString(r.renderBlocks(body))
			b.WriteString("</aside>\n")
			return b.String()
		}
	}

	return "<blockquote>\n" + r.renderBlocks(lines) + "</blockquote>\n"
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(strings.ToLower(s))
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func dropFirstNonBlank(lines []string) []string {
	out := append([]string(nil), lines...)
	for i, line := range out {
		if strings.TrimSpace(line) != "" {
			return out[i+1:]
		}
	}
	return nil
}

func listMarker(line string) (bool, string, bool) {
	trimmed := strings.TrimLeft(line, " ")
	if len(trimmed) >= 2 && (trimmed[0] == '-' || trimmed[0] == '*' || trimmed[0] == '+') && trimmed[1] == ' ' {
		return false, strings.TrimSpace(trimmed[2:]), true
	}
	i := 0
	for i < len(trimmed) && trimmed[i] >= '0' && trimmed[i] <= '9' {
		i++
	}
	if i > 0 && i+1 < len(trimmed) && trimmed[i] == '.' && trimmed[i+1] == ' ' {
		return true, strings.TrimSpace(trimmed[i+2:]), true
	}
	return false, "", false
}

func (r *MarkdownRenderer) renderListItem(content string) string {
	if strings.HasPrefix(content, "[ ] ") || strings.HasPrefix(strings.ToLower(content), "[x] ") {
		checked := strings.HasPrefix(strings.ToLower(content), "[x] ")
		rest := strings.TrimSpace(content[4:])
		box := `<input type="checkbox" disabled>`
		if checked {
			box = `<input type="checkbox" disabled checked>`
		}
		return box + " " + r.renderInline(rest)
	}
	return r.renderInline(content)
}

// mathBlock detects a display math block delimited by $$ and returns the LaTeX
// content lines (without the $$ fences) along with the index of the line that
// follows the block. Both the single-line form `$$ ... $$` and the multi-line
// form with `$$` on its own line are supported. The content is preserved
// verbatim so MathJax can typeset it on the client.
func mathBlock(lines []string, i int) ([]string, int, bool) {
	trimmed := strings.TrimSpace(lines[i])
	if !strings.HasPrefix(trimmed, "$$") {
		return nil, 0, false
	}
	rest := trimmed[2:]
	// Single-line: $$ ... $$
	if strings.HasSuffix(rest, "$$") && len(rest) >= 2 {
		return []string{strings.TrimSpace(rest[:len(rest)-2])}, i + 1, true
	}
	// Multi-line: opening $$ (optionally with trailing content) until closing $$.
	var body []string
	if head := strings.TrimSpace(rest); head != "" {
		body = append(body, head)
	}
	for j := i + 1; j < len(lines); j++ {
		lt := strings.TrimSpace(lines[j])
		if lt == "$$" {
			return body, j + 1, true
		}
		if strings.HasSuffix(lt, "$$") {
			body = append(body, strings.TrimSpace(strings.TrimSuffix(lt, "$$")))
			return body, j + 1, true
		}
		body = append(body, lines[j])
	}
	// Unterminated block: keep the remaining lines as math rather than mangling them.
	return body, len(lines), true
}

func isTableStart(lines []string, i int) bool {
	if i+1 >= len(lines) {
		return false
	}
	if !strings.Contains(lines[i], "|") {
		return false
	}
	return isTableSeparator(lines[i+1])
}

func isTableSeparator(line string) bool {
	cells := splitTableRow(line)
	if len(cells) == 0 {
		return false
	}
	for _, cell := range cells {
		cell = strings.TrimSpace(cell)
		if cell == "" {
			return false
		}
		cell = strings.Trim(cell, ":")
		if cell == "" {
			return false
		}
		for _, r := range cell {
			if r != '-' {
				return false
			}
		}
	}
	return true
}

func splitTableRow(line string) []string {
	line = strings.TrimSpace(line)
	line = strings.TrimPrefix(line, "|")
	line = strings.TrimSuffix(line, "|")
	parts := strings.Split(line, "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(parts[i])
	}
	return parts
}

// parseTableAlignments reads the separator row of a table and returns the
// CSS text-align value for each column. An empty string means no explicit
// alignment (the default).
func parseTableAlignments(line string) []string {
	cells := splitTableRow(line)
	aligns := make([]string, len(cells))
	for i, cell := range cells {
		cell = strings.TrimSpace(cell)
		left := strings.HasPrefix(cell, ":")
		right := strings.HasSuffix(cell, ":")
		switch {
		case left && right:
			aligns[i] = "center"
		case right:
			aligns[i] = "right"
		case left:
			aligns[i] = "left"
		}
	}
	return aligns
}

func alignAttr(aligns []string, i int) string {
	if i < len(aligns) && aligns[i] != "" {
		return ` style="text-align:` + aligns[i] + `"`
	}
	return ""
}

func (r *MarkdownRenderer) renderTable(lines []string) string {
	header := splitTableRow(lines[0])
	aligns := parseTableAlignments(lines[1])
	var b strings.Builder
	b.WriteString("<table>\n<thead><tr>")
	for i, cell := range header {
		b.WriteString("<th")
		b.WriteString(alignAttr(aligns, i))
		b.WriteString(">")
		b.WriteString(r.renderInline(cell))
		b.WriteString("</th>")
	}
	b.WriteString("</tr></thead>\n<tbody>\n")
	for _, line := range lines[2:] {
		cells := splitTableRow(line)
		if len(cells) == 0 {
			continue
		}
		b.WriteString("<tr>")
		for i, cell := range cells {
			b.WriteString("<td")
			b.WriteString(alignAttr(aligns, i))
			b.WriteString(">")
			b.WriteString(r.renderInline(cell))
			b.WriteString("</td>")
		}
		b.WriteString("</tr>\n")
	}
	b.WriteString("</tbody>\n</table>\n")
	return b.String()
}

func (r *MarkdownRenderer) uniqueHeadingID(base string) string {
	if base == "" {
		base = "section"
	}
	count := r.headingIDs[base]
	r.headingIDs[base] = count + 1
	if count == 0 {
		return base
	}
	return base + "-" + strconv.Itoa(count+1)
}

func (r *MarkdownRenderer) renderInline(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); {
		switch {
		case strings.HasPrefix(s[i:], "`"):
			if end := strings.Index(s[i+1:], "`"); end >= 0 {
				code := s[i+1 : i+1+end]
				b.WriteString("<code>")
				b.WriteString(html.EscapeString(code))
				b.WriteString("</code>")
				i += end + 2
				continue
			}
		case strings.HasPrefix(s[i:], "![["):
			if end := strings.Index(s[i+3:], "]]"); end >= 0 {
				raw := s[i+3 : i+3+end]
				b.WriteString(r.renderWiki(raw, true))
				i += end + 5
				continue
			}
		case strings.HasPrefix(s[i:], "[["):
			if end := strings.Index(s[i+2:], "]]"); end >= 0 {
				raw := s[i+2 : i+2+end]
				b.WriteString(r.renderWiki(raw, false))
				i += end + 4
				continue
			}
		case strings.HasPrefix(s[i:], "!["):
			if alt, dest, consumed, ok := parseMarkdownLink(s[i+1:]); ok {
				src := r.resolveMarkdownAsset(dest)
				b.WriteString(`<img src="`)
				b.WriteString(html.EscapeString(src))
				b.WriteString(`" alt="`)
				b.WriteString(html.EscapeString(stripInlineMarkdown(alt)))
				b.WriteString(`">`)
				i += consumed + 1
				continue
			}
		case strings.HasPrefix(s[i:], "["):
			if label, dest, consumed, ok := parseMarkdownLink(s[i:]); ok {
				href := r.resolveMarkdownHref(dest)
				b.WriteString(`<a href="`)
				b.WriteString(html.EscapeString(href))
				b.WriteString(`">`)
				b.WriteString(r.renderInline(label))
				b.WriteString(`</a>`)
				i += consumed
				continue
			}
		case strings.HasPrefix(s[i:], "https://") || strings.HasPrefix(s[i:], "http://"):
			href, consumed := consumeBareURL(s[i:])
			b.WriteString(`<a href="`)
			b.WriteString(html.EscapeString(sanitizeHref(href)))
			b.WriteString(`">`)
			b.WriteString(html.EscapeString(href))
			b.WriteString(`</a>`)
			i += consumed
			continue
		case strings.HasPrefix(s[i:], "**"):
			if end := strings.Index(s[i+2:], "**"); end >= 0 {
				b.WriteString("<strong>")
				b.WriteString(r.renderInline(s[i+2 : i+2+end]))
				b.WriteString("</strong>")
				i += end + 4
				continue
			}
		case strings.HasPrefix(s[i:], "__"):
			if end := strings.Index(s[i+2:], "__"); end >= 0 {
				b.WriteString("<strong>")
				b.WriteString(r.renderInline(s[i+2 : i+2+end]))
				b.WriteString("</strong>")
				i += end + 4
				continue
			}
		case strings.HasPrefix(s[i:], "*"):
			if end := strings.Index(s[i+1:], "*"); end >= 0 {
				b.WriteString("<em>")
				b.WriteString(r.renderInline(s[i+1 : i+1+end]))
				b.WriteString("</em>")
				i += end + 2
				continue
			}
		}

		rn, size := utf8.DecodeRuneInString(s[i:])
		if rn == utf8.RuneError && size == 0 {
			break
		}
		b.WriteString(html.EscapeString(string(rn)))
		i += size
	}
	return b.String()
}

func consumeBareURL(s string) (string, int) {
	end := 0
	for end < len(s) {
		r, size := utf8.DecodeRuneInString(s[end:])
		if unicode.IsSpace(r) || r == '<' || r == '"' {
			break
		}
		end += size
	}
	for end > 0 && strings.ContainsRune(".,;:", rune(s[end-1])) {
		end--
	}
	return s[:end], end
}

func parseMarkdownLink(s string) (string, string, int, bool) {
	if !strings.HasPrefix(s, "[") {
		return "", "", 0, false
	}
	closeLabel := strings.Index(s, "](")
	if closeLabel < 0 {
		return "", "", 0, false
	}
	closeDest := strings.Index(s[closeLabel+2:], ")")
	if closeDest < 0 {
		return "", "", 0, false
	}
	label := s[1:closeLabel]
	dest := s[closeLabel+2 : closeLabel+2+closeDest]
	return label, dest, closeLabel + 2 + closeDest + 1, true
}

func (r *MarkdownRenderer) renderWiki(raw string, embed bool) string {
	target, alias := splitAlias(raw)
	target, heading := splitHeading(target)
	display := alias
	if display == "" {
		display = heading
	}
	if display == "" {
		display = path.Base(strings.TrimSuffix(target, ".md"))
	}
	if display == "" {
		display = raw
	}

	if embed || looksLikeAsset(target) {
		if asset, ok := r.resolveAsset(target); ok {
			href := relativeURL(r.current, escapeURLPath(path.Join(r.vault.Config.sourcePrefix(), asset)))
			if isImage(asset) && embed {
				return `<img src="` + html.EscapeString(href) + `" alt="` + html.EscapeString(display) + `">`
			}
			return `<a href="` + html.EscapeString(href) + `">` + html.EscapeString(display) + `</a>`
		}
		if embed {
			if page := r.resolveNote(target); page != nil {
				r.outgoing[page.PageRel] = true
				return `<a class="embed-note" href="` + html.EscapeString(relativeURL(r.current, page.URL)) + `">` + html.EscapeString(display) + `</a>`
			}
		}
	}

	if page := r.resolveNote(target); page != nil {
		r.outgoing[page.PageRel] = true
		href := relativeURL(r.current, page.URL)
		if heading != "" {
			href += "#" + url.PathEscape(slugify(heading))
		}
		return `<a class="wiki-link" href="` + html.EscapeString(href) + `">` + html.EscapeString(display) + `</a>`
	}

	r.warn("unresolved wikilink [[" + raw + "]]")
	return `<span class="broken-link">[[` + html.EscapeString(raw) + `]]</span>`
}

func splitAlias(s string) (string, string) {
	target, alias, ok := strings.Cut(s, "|")
	if !ok {
		return strings.TrimSpace(s), ""
	}
	return strings.TrimSpace(target), strings.TrimSpace(alias)
}

func splitHeading(s string) (string, string) {
	target, heading, ok := strings.Cut(s, "#")
	if !ok {
		return strings.TrimSpace(s), ""
	}
	return strings.TrimSpace(target), strings.TrimSpace(heading)
}

func looksLikeAsset(target string) bool {
	ext := strings.ToLower(path.Ext(target))
	if strings.ContainsAny(ext, " \t") {
		return false
	}
	return ext != "" && ext != ".md"
}

func isImage(rel string) bool {
	switch strings.ToLower(path.Ext(rel)) {
	case ".avif", ".gif", ".jpeg", ".jpg", ".png", ".svg", ".webp":
		return true
	default:
		return false
	}
}

func (r *MarkdownRenderer) resolveNote(target string) *Page {
	target = strings.TrimSpace(strings.TrimSuffix(target, ".md"))
	if target == "" {
		return r.current
	}

	candidates := []string{}
	if path.Dir(r.current.PageRel) != "." {
		candidates = append(candidates, path.Join(path.Dir(r.current.PageRel), target))
	}
	candidates = append(candidates, target)
	for _, candidate := range candidates {
		if page := r.vault.ByPath[strings.ToLower(path.Clean(candidate))]; page != nil {
			return page
		}
	}

	if strings.Contains(target, "/") {
		return nil
	}

	matches := r.vault.ByBase[strings.ToLower(target)]
	if len(matches) == 0 {
		return nil
	}
	if len(matches) == 1 {
		return matches[0]
	}

	best := nearestPage(r.current, matches)
	if best == nil {
		r.warn("ambiguous wikilink [[" + target + "]]")
	}
	return best
}

func nearestPage(current *Page, matches []*Page) *Page {
	bestDistance := 1 << 30
	var best *Page
	tie := false
	for _, candidate := range matches {
		distance := folderDistance(path.Dir(current.PageRel), path.Dir(candidate.PageRel))
		if distance < bestDistance {
			bestDistance = distance
			best = candidate
			tie = false
		} else if distance == bestDistance {
			tie = true
		}
	}
	if tie {
		return nil
	}
	return best
}

func folderDistance(a, b string) int {
	if a == "." {
		a = ""
	}
	if b == "." {
		b = ""
	}
	ap := splitPath(a)
	bp := splitPath(b)
	common := 0
	for common < len(ap) && common < len(bp) && strings.EqualFold(ap[common], bp[common]) {
		common++
	}
	return (len(ap) - common) + (len(bp) - common)
}

func splitPath(s string) []string {
	if s == "" || s == "." {
		return nil
	}
	return strings.Split(s, "/")
}

func (r *MarkdownRenderer) resolveAsset(target string) (string, bool) {
	target = strings.TrimSpace(target)
	if target == "" {
		return "", false
	}
	target = strings.TrimPrefix(path.Clean(target), "./")
	var candidates []string
	if path.Dir(r.current.SourceRel) != "." {
		candidates = append(candidates, path.Join(path.Dir(r.current.SourceRel), target))
	}
	candidates = append(candidates, target)
	for _, candidate := range candidates {
		if rel, ok := r.vault.AssetsByPath[strings.ToLower(candidate)]; ok {
			return rel, true
		}
	}
	if strings.Contains(target, "/") {
		return "", false
	}
	matches := r.vault.AssetsByBase[strings.ToLower(path.Base(target))]
	if len(matches) == 1 {
		return matches[0], true
	}
	if len(matches) > 1 {
		currentDir := path.Dir(r.current.SourceRel)
		sort.Slice(matches, func(i, j int) bool {
			return folderDistance(currentDir, path.Dir(matches[i])) < folderDistance(currentDir, path.Dir(matches[j]))
		})
		if folderDistance(currentDir, path.Dir(matches[0])) != folderDistance(currentDir, path.Dir(matches[1])) {
			return matches[0], true
		}
		r.warn("ambiguous asset [[" + target + "]]")
	}
	return "", false
}

func (r *MarkdownRenderer) resolveMarkdownHref(dest string) string {
	dest = strings.TrimSpace(dest)
	if isExternalOrAbsolute(dest) || strings.HasPrefix(dest, "#") {
		return sanitizeHref(dest)
	}

	cleanDest, anchor := splitURLAnchor(dest)
	if strings.EqualFold(path.Ext(cleanDest), ".md") {
		target := strings.TrimSuffix(cleanDest, ".md")
		candidates := []string{}
		if !strings.HasPrefix(target, "/") && path.Dir(r.current.PageRel) != "." {
			candidates = append(candidates, path.Join(path.Dir(r.current.PageRel), target))
		}
		candidates = append(candidates, strings.TrimPrefix(target, "/"))
		for _, candidate := range candidates {
			if page := r.vault.ByPath[strings.ToLower(path.Clean(candidate))]; page != nil {
				href := relativeURL(r.current, page.URL)
				if anchor != "" {
					href += "#" + url.PathEscape(slugify(anchor))
				}
				r.outgoing[page.PageRel] = true
				return href
			}
		}
	}

	return r.resolveMarkdownAsset(dest)
}

func (r *MarkdownRenderer) resolveMarkdownAsset(dest string) string {
	dest = strings.TrimSpace(dest)
	if isExternalOrAbsolute(dest) || strings.HasPrefix(dest, "#") {
		return sanitizeHref(dest)
	}
	cleanDest, anchor := splitURLAnchor(dest)
	if path.Dir(r.current.SourceRel) != "." && !strings.HasPrefix(cleanDest, "/") {
		cleanDest = path.Join(path.Dir(r.current.SourceRel), cleanDest)
	}
	cleanDest = strings.TrimPrefix(path.Clean(cleanDest), "/")
	href := relativeURL(r.current, escapeURLPath(path.Join(r.vault.Config.sourcePrefix(), cleanDest)))
	if anchor != "" {
		href += "#" + url.PathEscape(anchor)
	}
	return href
}

func splitURLAnchor(s string) (string, string) {
	before, after, ok := strings.Cut(s, "#")
	if !ok {
		return s, ""
	}
	return before, after
}

func isExternalOrAbsolute(s string) bool {
	lower := strings.ToLower(s)
	return strings.HasPrefix(lower, "http://") ||
		strings.HasPrefix(lower, "https://") ||
		strings.HasPrefix(lower, "mailto:") ||
		strings.HasPrefix(lower, "tel:") ||
		strings.HasPrefix(s, "/")
}

func sanitizeHref(href string) string {
	lower := strings.ToLower(strings.TrimSpace(href))
	if strings.HasPrefix(lower, "javascript:") || strings.HasPrefix(lower, "data:") {
		return "#"
	}
	return href
}

func (r *MarkdownRenderer) warn(message string) {
	*r.warnings = append(*r.warnings, r.current.SourceRel+": "+message)
}

func stripInlineMarkdown(s string) string {
	wikiRE := regexp.MustCompile(`!?\[\[([^|\]#]+)(?:#[^|\]]*)?(?:\|([^\]]+))?\]\]`)
	s = wikiRE.ReplaceAllStringFunc(s, func(match string) string {
		m := wikiRE.FindStringSubmatch(match)
		if len(m) > 2 && m[2] != "" {
			return m[2]
		}
		return path.Base(m[1])
	})
	linkRE := regexp.MustCompile(`!?\[([^\]]*)\]\([^)]+\)`)
	s = linkRE.ReplaceAllString(s, "$1")
	for _, marker := range []string{"**", "__", "*", "`"} {
		s = strings.ReplaceAll(s, marker, "")
	}
	return strings.TrimSpace(s)
}

func plainText(markdown string) string {
	text := stripInlineMarkdown(markdown)
	lines := strings.Split(text, "\n")
	out := make([]string, 0, len(lines))
	inFence := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			inFence = !inFence
			continue
		}
		if inFence || trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, ">") {
			trimmed = strings.TrimSpace(strings.TrimPrefix(trimmed, ">"))
		}
		out = append(out, strings.Trim(trimmed, "#-* "))
	}
	return strings.Join(strings.Fields(strings.Join(out, " ")), " ")
}

func extractTags(markdown string) []string {
	re := regexp.MustCompile(`(^|\s)#([A-Za-z0-9_/-]+)`)
	matches := re.FindAllStringSubmatch(markdown, -1)
	seen := map[string]bool{}
	var tags []string
	for _, match := range matches {
		tag := match[2]
		if tag == "" || seen[tag] {
			continue
		}
		seen[tag] = true
		tags = append(tags, tag)
	}
	sort.Strings(tags)
	return tags
}

func excerpt(text string, limit int) string {
	text = strings.TrimSpace(strings.Join(strings.Fields(text), " "))
	if len(text) <= limit {
		return text
	}
	return strings.TrimSpace(text[:limit]) + "..."
}

func slugify(s string) string {
	s = strings.ToLower(stripInlineMarkdown(s))
	var b strings.Builder
	lastDash := false
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash {
			b.WriteRune('-')
			lastDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

func escapeURLPath(rel string) string {
	rel = strings.TrimPrefix(path.Clean(strings.ReplaceAll(rel, "\\", "/")), "/")
	if rel == "." || rel == "" {
		return ""
	}
	parts := strings.Split(rel, "/")
	for i, part := range parts {
		parts[i] = url.PathEscape(part)
	}
	return strings.Join(parts, "/")
}

func relativeRoot(from *Page) string {
	if from == nil || from.IsHome || from.URL == "" {
		return ""
	}
	trimmed := strings.Trim(strings.TrimSuffix(from.URL, "/"), "/")
	if trimmed == "" {
		return ""
	}
	levels := len(strings.Split(trimmed, "/"))
	return strings.Repeat("../", levels)
}

func relativeURL(from *Page, target string) string {
	target = strings.TrimPrefix(target, "/")
	root := relativeRoot(from)
	if target == "" {
		if root == "" {
			return "./"
		}
		return root
	}
	return root + target
}

const defaultPageTemplate = `{{.Generated}}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{if .Page.IsHome}}{{.Site.Title}}{{else}}{{.Page.Title}} - {{.Site.Title}}{{end}}</title>
  <link rel="stylesheet" href="{{.CSSURL}}">
  <script>window.ONYX_ROOT = {{.RootScript}}; window.ONYX_PAGE = {{.PageID}};</script>
  {{if or .Search .Graph}}<script defer src="{{.JSURL}}"></script>{{end}}{{if .Page.HasMath}}<script async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>{{end}}
</head>
<body>
  <a class="skip-link" href="#content">Skip to content</a>
  <div class="onyx-shell">
    <aside class="onyx-sidebar">
      <a class="onyx-brand" href="{{.HomeURL}}">{{.Site.Title}}</a>
      {{if .Search}}
      <div class="onyx-search">
        <input id="onyx-search" type="search" autocomplete="off" placeholder="Search notes">
        <div id="onyx-search-results" class="onyx-search-results" hidden></div>
      </div>
      {{end}}
      {{if .Graph}}
      <button type="button" id="onyx-graph-open" class="onyx-graph-btn" aria-haspopup="dialog">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">
          <circle cx="5" cy="6" r="2.2"></circle>
          <circle cx="18" cy="7" r="2.2"></circle>
          <circle cx="12" cy="17" r="2.2"></circle>
          <line x1="6.8" y1="7.2" x2="10.4" y2="15.4"></line>
          <line x1="16.4" y1="8.6" x2="13.3" y2="15.5"></line>
          <line x1="7" y1="6.5" x2="16" y2="6.8"></line>
        </svg>
        Graph view
      </button>
      {{end}}
      <nav aria-label="Notes">
        {{.Nav}}
      </nav>
    </aside>
    <main id="content" class="onyx-main">
      <article class="onyx-note">
        <header class="onyx-note-header">
          {{if .Page.SourceRel}}<p class="onyx-path">{{.Page.SourceRel}}</p>{{end}}
          <h1>{{.Page.Title}}</h1>
          {{if .ShowSource}}<a class="onyx-source" href="{{.Page.SourceURL}}">Markdown</a>{{end}}
        </header>
        <div class="onyx-content">
          {{.Page.HTML}}
        </div>
        {{if and .Backlinks .Site.Title}}
        <section class="onyx-backlinks" aria-labelledby="backlinks-title">
          <h2 id="backlinks-title">Linked From</h2>
          <ul>
            {{range .Backlinks}}<li><a href="{{.URL}}">{{.Title}}</a> <span>{{.Path}}</span></li>{{end}}
          </ul>
        </section>
        {{end}}
      </article>
    </main>
  </div>
  {{if .Graph}}
  <div id="onyx-graph-modal" class="onyx-graph-modal" hidden role="dialog" aria-modal="true" aria-label="Knowledge graph">
    <div class="onyx-graph-backdrop" data-graph-close></div>
    <div class="onyx-graph-panel">
      <div class="onyx-graph-toolbar">
        <span class="onyx-graph-title">Graph</span>
        <span class="onyx-graph-hint">drag to pan &middot; scroll to zoom &middot; click a node to open</span>
        <button type="button" class="onyx-graph-close" data-graph-close aria-label="Close graph">&times;</button>
      </div>
      <canvas id="onyx-graph-canvas"></canvas>
    </div>
  </div>
  {{end}}
</body>
</html>
`

const defaultCSS = `:root {
  color-scheme: light;
  --bg: #f7f5ef;
  --panel: #efece3;
  --text: #20201d;
  --muted: #6d6a60;
  --line: #ddd7ca;
  --accent: #2f6f73;
  --accent-2: #8a5a35;
  --code: #ece5d8;
  --warn: #9a3412;
  --hover: #fdf6e7;
  --active: #f4ead3;
  --ring: rgb(47 111 115 / 22%);
  --radius: 8px;
  --graph-node: #9a948733;
  --graph-node-solid: #8c867a;
  --graph-link: rgb(109 106 96 / 28%);
  --graph-current: var(--accent);
  --graph-focus: var(--accent-2);
  --graph-label: #4a4740;
  --graph-backdrop: rgb(24 23 20 / 55%);
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

:focus-visible {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}

* { box-sizing: border-box; }
html { min-height: 100%; }
body {
  min-height: 100%;
  margin: 0;
  background: var(--bg);
  color: var(--text);
  line-height: 1.65;
}

a { color: var(--accent); text-decoration-thickness: .08em; text-underline-offset: .18em; }
a:hover { color: var(--accent-2); }

.skip-link {
  position: absolute;
  top: .75rem;
  left: .75rem;
  transform: translateY(-200%);
  background: var(--text);
  color: var(--bg);
  padding: .45rem .7rem;
  border-radius: 6px;
  z-index: 10;
}
.skip-link:focus { transform: translateY(0); }

.onyx-shell {
  display: grid;
  grid-template-columns: minmax(17rem, 22rem) minmax(0, 1fr);
  min-height: 100vh;
}

.onyx-sidebar {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
  border-right: 1px solid var(--line);
  background: var(--panel);
  padding: 1.1rem;
}

.onyx-brand {
  display: block;
  color: var(--text);
  font-size: 1.05rem;
  font-weight: 750;
  line-height: 1.2;
  margin-bottom: 1rem;
  text-decoration: none;
}

.onyx-search { position: relative; margin-bottom: 1rem; }
.onyx-search input {
  width: 100%;
  border: 1px solid var(--line);
  border-radius: 7px;
  background: #fffdfa;
  color: var(--text);
  font: inherit;
  line-height: 1.2;
  padding: .55rem .65rem;
  transition: border-color .12s ease, box-shadow .12s ease;
}
.onyx-search input:focus {
  outline: none;
  border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--ring);
}
.onyx-search-results {
  position: absolute;
  z-index: 5;
  top: calc(100% + .35rem);
  left: 0;
  right: 0;
  max-height: 60vh;
  overflow: auto;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: #fffdfa;
  box-shadow: 0 14px 28px rgb(32 32 29 / 15%);
}
.onyx-search-results a {
  display: block;
  padding: .65rem .75rem;
  color: var(--text);
  text-decoration: none;
  border-bottom: 1px solid var(--line);
}
.onyx-search-results a:last-child { border-bottom: 0; }
.onyx-search-results strong { display: block; line-height: 1.25; }
.onyx-search-results span {
  display: block;
  color: var(--muted);
  font-size: .82rem;
  line-height: 1.35;
  margin-top: .15rem;
}

.nav-tree, .nav-tree ul {
  list-style: none;
  margin: 0;
  padding-left: 0;
}
.nav-tree ul {
  margin-left: .55rem;
  padding-left: .55rem;
  border-left: 1px solid var(--line);
}
.nav-tree li { margin: .05rem 0; }
.nav-tree a, .nav-tree span, .nav-tree summary {
  display: flex;
  align-items: center;
  gap: .5rem;
  color: var(--muted);
  font-size: .92rem;
  line-height: 1.3;
  padding: .28rem .45rem;
  text-decoration: none;
  border-radius: 7px;
  transition: background .12s ease, color .12s ease;
}
.nav-tree a:hover, .nav-tree summary:hover { background: var(--hover); color: var(--text); }
.nav-tree a[aria-current="page"] {
  background: var(--active);
  color: var(--accent);
  font-weight: 700;
}

/* Folder rows: a caret that rotates open, with a folder-toned label. */
.nav-tree details { margin: .05rem 0; }
.nav-tree summary {
  cursor: pointer;
  list-style: none;
  font-weight: 600;
  color: var(--text);
}
.nav-tree summary::-webkit-details-marker { display: none; }
.nav-tree summary::before {
  content: "";
  flex: 0 0 auto;
  width: 0;
  height: 0;
  border-left: 5px solid currentColor;
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  opacity: .5;
  transition: transform .15s ease;
}
.nav-tree details[open] > summary::before { transform: rotate(90deg); }
.nav-tree summary a, .nav-tree summary span {
  display: inline;
  gap: 0;
  padding: 0;
  color: inherit;
  font: inherit;
}
.nav-tree summary a:hover { background: none; color: inherit; }

/* File rows: a small square dot, filled when it's the current page. */
.nav-tree li > a::before {
  content: "";
  flex: 0 0 auto;
  width: .4rem;
  height: .4rem;
  margin: 0 .05rem;
  border-radius: 2px;
  background: currentColor;
  opacity: .35;
}
.nav-tree li > a:hover::before { opacity: .6; }
.nav-tree li > a[aria-current="page"]::before { opacity: 1; }

.onyx-main {
  width: min(100%, 78rem);
  padding: clamp(1.2rem, 4vw, 4rem);
}
.onyx-note {
  max-width: 52rem;
}
.onyx-note-header {
  border-bottom: 1px solid var(--line);
  margin-bottom: 1.35rem;
  padding-bottom: 1rem;
}
.onyx-path {
  color: var(--muted);
  font-size: .85rem;
  line-height: 1.2;
  margin: 0 0 .35rem;
}
.onyx-note h1 {
  font-size: clamp(2rem, 5vw, 3.2rem);
  letter-spacing: 0;
  line-height: 1.05;
  margin: 0;
}
.onyx-source {
  display: inline-block;
  font-size: .86rem;
  margin-top: .65rem;
}

.onyx-content h2, .onyx-content h3, .onyx-content h4 {
  line-height: 1.15;
  margin-top: 2rem;
}
.onyx-content p, .onyx-content ul, .onyx-content ol, .onyx-content blockquote, .onyx-content table, .onyx-content pre {
  margin-bottom: 1rem;
}
.onyx-content img {
  max-width: 100%;
  height: auto;
  border-radius: 8px;
}
.onyx-content code {
  background: var(--code);
  border-radius: 5px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: .92em;
  padding: .08rem .25rem;
}
.onyx-content pre {
  background: #24231f;
  color: #f7f5ef;
  overflow: auto;
  padding: 1rem;
  border-radius: 8px;
}
.onyx-content pre code {
  background: transparent;
  color: inherit;
  padding: 0;
}
.onyx-content blockquote {
  border-left: 3px solid var(--line);
  color: var(--muted);
  margin-left: 0;
  padding-left: 1rem;
}
.onyx-content table {
  border-collapse: collapse;
  display: block;
  max-width: 100%;
  overflow-x: auto;
}
.onyx-content th, .onyx-content td {
  border: 1px solid var(--line);
  padding: .45rem .6rem;
  vertical-align: top;
}
.onyx-content th { background: var(--panel); text-align: left; }
.onyx-content .onyx-math {
  margin: 1.1rem 0;
  overflow-x: auto;
  overflow-y: hidden;
}

.callout {
  border: 1px solid var(--line);
  border-left: 4px solid var(--accent);
  border-radius: 8px;
  margin: 1rem 0;
  padding: .8rem 1rem;
  background: #fffdfa;
}
.callout-title {
  color: var(--accent);
  font-weight: 800;
  margin: 0 0 .35rem;
}
.callout-warning, .callout-danger, .callout-caution { border-left-color: var(--warn); }
.callout-warning .callout-title, .callout-danger .callout-title, .callout-caution .callout-title { color: var(--warn); }

.broken-link {
  color: var(--warn);
  font-weight: 700;
}
.embed-note {
  border: 1px solid var(--line);
  border-radius: 6px;
  display: inline-block;
  padding: .05rem .35rem;
  text-decoration: none;
}

.onyx-backlinks {
  border-top: 1px solid var(--line);
  margin-top: 2rem;
  padding-top: 1rem;
}
.onyx-backlinks h2 {
  font-size: 1rem;
  letter-spacing: 0;
  margin: 0 0 .5rem;
}
.onyx-backlinks ul { padding-left: 1.1rem; }
.onyx-backlinks span {
  color: var(--muted);
  font-size: .85rem;
}

/* Graph view: a sidebar trigger that opens a full-screen force-directed map. */
.onyx-graph-btn {
  display: flex;
  align-items: center;
  gap: .5rem;
  width: 100%;
  margin-bottom: 1rem;
  padding: .5rem .65rem;
  border: 1px solid var(--line);
  border-radius: 7px;
  background: #fffdfa;
  color: var(--text);
  font: inherit;
  line-height: 1.2;
  cursor: pointer;
  transition: background .12s ease, border-color .12s ease, color .12s ease;
}
.onyx-graph-btn:hover { background: var(--hover); border-color: var(--accent); color: var(--accent); }
.onyx-graph-btn svg { width: 1.1em; height: 1.1em; flex: 0 0 auto; opacity: .85; }

.onyx-graph-modal { position: fixed; inset: 0; z-index: 50; display: flex; }
.onyx-graph-modal[hidden] { display: none; }
.onyx-graph-backdrop {
  position: absolute;
  inset: 0;
  background: var(--graph-backdrop);
  -webkit-backdrop-filter: blur(2px);
  backdrop-filter: blur(2px);
}
.onyx-graph-panel {
  position: relative;
  margin: auto;
  width: min(94vw, 1100px);
  height: min(88vh, 780px);
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: var(--bg);
  border: 1px solid var(--line);
  border-radius: 14px;
  box-shadow: 0 24px 60px rgb(24 23 20 / 38%);
  animation: onyx-graph-pop .16s ease;
}
@keyframes onyx-graph-pop {
  from { opacity: 0; transform: translateY(8px) scale(.99); }
  to { opacity: 1; transform: none; }
}
.onyx-graph-toolbar {
  display: flex;
  align-items: center;
  gap: .75rem;
  padding: .55rem .9rem;
  border-bottom: 1px solid var(--line);
  background: var(--panel);
}
.onyx-graph-title { font-weight: 750; }
.onyx-graph-hint { color: var(--muted); font-size: .8rem; margin-right: auto; }
.onyx-graph-close {
  border: 0;
  background: transparent;
  color: var(--muted);
  cursor: pointer;
  font-size: 1.5rem;
  line-height: 1;
  padding: 0 .25rem;
  border-radius: 6px;
}
.onyx-graph-close:hover { color: var(--text); background: var(--hover); }
#onyx-graph-canvas {
  flex: 1 1 auto;
  width: 100%;
  height: 100%;
  display: block;
  background: var(--bg);
  cursor: grab;
  touch-action: none;
}
#onyx-graph-canvas.is-grabbing { cursor: grabbing; }
#onyx-graph-canvas.is-pointing { cursor: pointer; }
body.onyx-graph-lock { overflow: hidden; }

@media (max-width: 820px) {
  .onyx-shell { display: block; }
  .onyx-sidebar {
    position: static;
    height: auto;
    max-height: 45vh;
    border-right: 0;
    border-bottom: 1px solid var(--line);
  }
  .onyx-main { padding: 1.2rem; }
  .onyx-note h1 { font-size: 2rem; }
  .onyx-graph-panel { width: 96vw; height: 90vh; }
  .onyx-graph-hint { display: none; }
}
`

const defaultJS = `(function () {
  const input = document.getElementById("onyx-search");
  const results = document.getElementById("onyx-search-results");
  if (!input || !results) return;

  const root = window.ONYX_ROOT || "";
  let index = [];

  fetch(root + "public/search-index.json")
    .then((response) => response.ok ? response.json() : [])
    .then((items) => { index = Array.isArray(items) ? items : []; })
    .catch(() => { index = []; });

  function escapeHTML(value) {
    return String(value).replace(/[&<>"']/g, (ch) => ({
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;"
    })[ch]);
  }

  function score(item, terms) {
    const haystack = [
      item.title || "",
      item.path || "",
      item.excerpt || "",
      (item.headings || []).join(" "),
      (item.tags || []).join(" ")
    ].join(" ").toLowerCase();
    let total = 0;
    for (const term of terms) {
      if (!haystack.includes(term)) return 0;
      total += (item.title || "").toLowerCase().includes(term) ? 4 : 1;
      total += (item.path || "").toLowerCase().includes(term) ? 2 : 0;
    }
    return total;
  }

  function withRoot(url) {
    return root + (url || "./");
  }

  function render() {
    const terms = input.value.trim().toLowerCase().split(/\s+/).filter(Boolean);
    if (!terms.length) {
      results.hidden = true;
      results.innerHTML = "";
      return;
    }
    const matches = index
      .map((item) => ({ item, value: score(item, terms) }))
      .filter((entry) => entry.value > 0)
      .sort((a, b) => b.value - a.value || String(a.item.title).localeCompare(String(b.item.title)))
      .slice(0, 12);

    results.innerHTML = matches.length
      ? matches.map(({ item }) => '<a href="' + escapeHTML(withRoot(item.url)) + '"><strong>' + escapeHTML(item.title) + '</strong><span>' + escapeHTML(item.excerpt || item.path || "") + '</span></a>').join("")
      : '<a href="#"><strong>No matches</strong><span>Try a different phrase.</span></a>';
    results.hidden = false;
  }

  input.addEventListener("input", render);
  input.addEventListener("focus", render);
  document.addEventListener("click", (event) => {
    if (!results.contains(event.target) && event.target !== input) results.hidden = true;
  });
  document.addEventListener("keydown", (event) => {
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
      event.preventDefault();
      input.focus();
      input.select();
    }
    if (event.key === "Escape") {
      results.hidden = true;
      input.blur();
    }
  });
})();

(function () {
  var modal = document.getElementById("onyx-graph-modal");
  var canvas = document.getElementById("onyx-graph-canvas");
  var openBtn = document.getElementById("onyx-graph-open");
  if (!modal || !canvas) return;

  var root = window.ONYX_ROOT || "";
  var currentId = window.ONYX_PAGE || "";
  var ctx = canvas.getContext("2d");

  var nodes = [];
  var links = [];
  var nodeById = new Map();
  var loaded = false;
  var loading = false;

  var timer = null;
  var dirty = true;
  var alpha = 0;
  var alphaMin = 0.0015;

  var scale = 1, offsetX = 0, offsetY = 0;
  var dpr = 1;
  var hoverNode = null, dragNode = null, panning = false;
  var pressX = 0, pressY = 0, lastX = 0, lastY = 0, moved = false;
  var colors = {};

  function radiusOf(n) { return 3 + Math.sqrt(n.degree) * 1.7; }

  function load() {
    if (loaded || loading) return;
    loading = true;
    fetch(root + "public/graph.json")
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (data) {
        build(data || { nodes: [], links: [] });
        loaded = true;
        loading = false;
        layout();
      })
      .catch(function () { loading = false; });
  }

  function build(data) {
    nodeById = new Map();
    var w = canvas.clientWidth || 800;
    var h = canvas.clientHeight || 600;
    nodes = (data.nodes || []).map(function (n, i) {
      var ang = i * 2.3999632;
      var rad = 16 + Math.sqrt(i + 1) * 16;
      var node = {
        id: n.id,
        title: n.title || n.id,
        url: n.url || "",
        degree: n.degree || 0,
        x: w / 2 + Math.cos(ang) * rad,
        y: h / 2 + Math.sin(ang) * rad,
        vx: 0, vy: 0,
        neighbors: new Set()
      };
      nodeById.set(n.id, node);
      return node;
    });
    links = (data.links || []).map(function (l) {
      return { source: nodeById.get(l.source), target: nodeById.get(l.target) };
    }).filter(function (l) { return l.source && l.target; });
    links.forEach(function (l) { l.source.neighbors.add(l.target); l.target.neighbors.add(l.source); });
  }

  function tick() {
    alpha += (0 - alpha) * 0.0228;
    var i, j, a, b, dx, dy, d2, dist, f, w;
    var charge = -60;
    for (i = 0; i < nodes.length; i++) {
      a = nodes[i];
      for (j = i + 1; j < nodes.length; j++) {
        b = nodes[j];
        dx = b.x - a.x; dy = b.y - a.y;
        d2 = dx * dx + dy * dy;
        // Floor the distance so two near-coincident nodes never produce a
        // runaway impulse (without this the layout diverges to infinity).
        if (d2 < 1) { dx = Math.random() - 0.5; dy = Math.random() - 0.5; d2 = dx * dx + dy * dy + 1; }
        w = charge * alpha / d2;
        a.vx += dx * w; a.vy += dy * w;
        b.vx -= dx * w; b.vy -= dy * w;
      }
    }
    var linkDist = 46, linkStr = 0.4;
    for (i = 0; i < links.length; i++) {
      a = links[i].source; b = links[i].target;
      dx = b.x - a.x; dy = b.y - a.y;
      dist = Math.sqrt(dx * dx + dy * dy) || 1;
      f = (dist - linkDist) / dist * alpha * linkStr;
      dx *= f; dy *= f;
      b.vx -= dx; b.vy -= dy;
      a.vx += dx; a.vy += dy;
    }
    var cx = canvas.clientWidth / 2, cy = canvas.clientHeight / 2, g = 0.05 * alpha;
    var maxV = 50;
    for (i = 0; i < nodes.length; i++) {
      a = nodes[i];
      a.vx += (cx - a.x) * g;
      a.vy += (cy - a.y) * g;
      if (a === dragNode) { a.vx = 0; a.vy = 0; continue; }
      a.vx *= 0.6; a.vy *= 0.6;
      var sp = a.vx * a.vx + a.vy * a.vy;
      if (sp > maxV * maxV) { var s = maxV / Math.sqrt(sp); a.vx *= s; a.vy *= s; }
      a.x += a.vx; a.y += a.vy;
    }
  }

  function layout() {
    alpha = 1;
    for (var k = 0; k < 140; k++) tick();
    fit();
    dirty = true;
  }

  function fit() {
    if (!nodes.length) return;
    var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (var i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      if (n.x < minX) minX = n.x;
      if (n.x > maxX) maxX = n.x;
      if (n.y < minY) minY = n.y;
      if (n.y > maxY) maxY = n.y;
    }
    var w = canvas.clientWidth || 800, h = canvas.clientHeight || 600;
    var gw = (maxX - minX) || 1, gh = (maxY - minY) || 1;
    var pad = 80;
    scale = Math.min((w - pad) / gw, (h - pad) / gh);
    if (!isFinite(scale) || scale <= 0) scale = 1;
    scale = Math.max(0.15, Math.min(scale, 2.2));
    offsetX = w / 2 - ((minX + maxX) / 2) * scale;
    offsetY = h / 2 - ((minY + maxY) / 2) * scale;
  }

  function readColors() {
    var s = getComputedStyle(document.documentElement);
    function v(name, fallback) { var c = s.getPropertyValue(name).trim(); return c || fallback; }
    colors.link = v("--graph-link", "rgba(120,118,108,0.3)");
    colors.current = v("--graph-current", "#2f6f73");
    colors.focus = v("--graph-focus", "#8a5a35");
    colors.node = v("--graph-node-solid", "#8c867a");
    colors.label = v("--graph-label", "#4a4740");
  }

  function draw() {
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.setTransform(dpr * scale, 0, 0, dpr * scale, dpr * offsetX, dpr * offsetY);

    var focus = hoverNode;
    var i, n;

    ctx.lineWidth = 1 / scale;
    for (i = 0; i < links.length; i++) {
      var s = links[i].source, t = links[i].target;
      var active = focus && (s === focus || t === focus);
      ctx.strokeStyle = active ? colors.current : colors.link;
      ctx.globalAlpha = focus ? (active ? 0.9 : 0.12) : 1;
      ctx.beginPath();
      ctx.moveTo(s.x, s.y);
      ctx.lineTo(t.x, t.y);
      ctx.stroke();
    }

    for (i = 0; i < nodes.length; i++) {
      n = nodes[i];
      var isCurrent = n.id === currentId;
      var related = focus && (n === focus || focus.neighbors.has(n));
      var r = radiusOf(n);
      if (n === focus) r += 1.5 / scale + 1.5;
      ctx.globalAlpha = focus ? (related ? 1 : 0.22) : 1;
      ctx.fillStyle = isCurrent ? colors.current : (related ? colors.focus : colors.node);
      ctx.beginPath();
      ctx.arc(n.x, n.y, r, 0, Math.PI * 2);
      ctx.fill();
      if (isCurrent) {
        ctx.globalAlpha = focus ? (related ? 1 : 0.4) : 1;
        ctx.lineWidth = 2 / scale;
        ctx.strokeStyle = colors.current;
        ctx.beginPath();
        ctx.arc(n.x, n.y, r + 4 / scale, 0, Math.PI * 2);
        ctx.stroke();
      }
    }
    ctx.globalAlpha = 1;

    var fontPx = 11 / scale;
    ctx.font = fontPx + "px ui-sans-serif, system-ui, -apple-system, sans-serif";
    ctx.textAlign = "center";
    ctx.textBaseline = "top";
    ctx.fillStyle = colors.label;
    var showAll = scale > 1.25;
    for (i = 0; i < nodes.length; i++) {
      n = nodes[i];
      var rel = focus && (n === focus || focus.neighbors.has(n));
      var hub = n.degree >= 7;
      var show = rel || n.id === currentId || (!focus && (hub || showAll));
      if (!show) continue;
      ctx.globalAlpha = focus ? (rel ? 1 : 0.18) : (n.id === currentId ? 1 : 0.8);
      ctx.fillText(n.title, n.x, n.y + radiusOf(n) + 3 / scale);
    }
    ctx.globalAlpha = 1;
  }

  // A timer drives the loop rather than requestAnimationFrame so the first
  // paint never depends on the tab being actively composited. While the layout
  // is settling we tick + redraw; once settled we only redraw when something
  // changed (hover, pan, zoom, drag), keeping an idle graph near-zero cost.
  function step() {
    if (alpha > alphaMin) { tick(); draw(); }
    else if (dirty) { draw(); dirty = false; }
  }
  function start() { if (!timer) timer = setInterval(step, 1000 / 60); }
  function stop() { if (timer) { clearInterval(timer); timer = null; } }
  function reheat(a) { if (a > alpha) alpha = a; dirty = true; }

  function resize() {
    dpr = Math.max(1, window.devicePixelRatio || 1);
    var w = canvas.clientWidth, h = canvas.clientHeight;
    canvas.width = Math.round(w * dpr);
    canvas.height = Math.round(h * dpr);
  }

  function isOpen() { return !modal.hidden; }

  function open() {
    modal.hidden = false;
    document.body.classList.add("onyx-graph-lock");
    readColors();
    resize();
    load();
    if (loaded) { fit(); reheat(0.3); }
    start();
    dirty = true;
    draw();
  }

  function close() {
    modal.hidden = true;
    document.body.classList.remove("onyx-graph-lock");
    stop();
    hoverNode = null;
    dragNode = null;
    panning = false;
    canvas.classList.remove("is-grabbing", "is-pointing");
  }

  function toWorld(clientX, clientY) {
    var rect = canvas.getBoundingClientRect();
    return { x: (clientX - rect.left - offsetX) / scale, y: (clientY - rect.top - offsetY) / scale };
  }

  function pick(wx, wy) {
    var best = null, bestD = Infinity;
    for (var i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      var r = radiusOf(n) + 4 / scale;
      var dx = n.x - wx, dy = n.y - wy, d = dx * dx + dy * dy;
      if (d <= r * r && d < bestD) { bestD = d; best = n; }
    }
    return best;
  }

  function navigate(n) {
    if (!n) return;
    window.location.href = root + (n.url || "") || "./";
  }

  canvas.addEventListener("pointerdown", function (e) {
    try { canvas.setPointerCapture(e.pointerId); } catch (err) {}
    pressX = e.clientX; pressY = e.clientY;
    lastX = e.clientX; lastY = e.clientY;
    moved = false;
    var p = toWorld(e.clientX, e.clientY);
    var n = pick(p.x, p.y);
    if (n) { dragNode = n; reheat(0.4); } else { panning = true; }
    canvas.classList.add("is-grabbing");
    dirty = true;
  });

  canvas.addEventListener("pointermove", function (e) {
    if (Math.abs(e.clientX - pressX) + Math.abs(e.clientY - pressY) > 3) moved = true;
    var mvx = e.movementX !== undefined ? e.movementX : e.clientX - lastX;
    var mvy = e.movementY !== undefined ? e.movementY : e.clientY - lastY;
    lastX = e.clientX; lastY = e.clientY;
    if (dragNode) {
      var p = toWorld(e.clientX, e.clientY);
      dragNode.x = p.x; dragNode.y = p.y; dragNode.vx = 0; dragNode.vy = 0;
      reheat(0.3);
    } else if (panning) {
      offsetX += mvx; offsetY += mvy;
    } else {
      var q = toWorld(e.clientX, e.clientY);
      var hit = pick(q.x, q.y);
      hoverNode = hit;
      canvas.classList.toggle("is-pointing", !!hit);
    }
    dirty = true;
  });

  function endPointer(e) {
    if (dragNode && !moved) navigate(dragNode);
    dragNode = null;
    panning = false;
    canvas.classList.remove("is-grabbing");
    try { canvas.releasePointerCapture(e.pointerId); } catch (err) {}
  }
  canvas.addEventListener("pointerup", endPointer);
  canvas.addEventListener("pointercancel", endPointer);

  canvas.addEventListener("wheel", function (e) {
    e.preventDefault();
    var rect = canvas.getBoundingClientRect();
    var sx = e.clientX - rect.left, sy = e.clientY - rect.top;
    var wx = (sx - offsetX) / scale, wy = (sy - offsetY) / scale;
    var factor = Math.exp(-e.deltaY * 0.0012);
    scale = Math.max(0.1, Math.min(scale * factor, 6));
    offsetX = sx - wx * scale;
    offsetY = sy - wy * scale;
    dirty = true;
  }, { passive: false });

  if (openBtn) openBtn.addEventListener("click", open);
  modal.addEventListener("click", function (e) {
    if (e.target && e.target.hasAttribute && e.target.hasAttribute("data-graph-close")) close();
  });
  window.addEventListener("resize", function () { if (isOpen()) { resize(); dirty = true; } });
  document.addEventListener("keydown", function (e) {
    var el = document.activeElement;
    var tag = (el && el.tagName) || "";
    var typing = tag === "INPUT" || tag === "TEXTAREA" || (el && el.isContentEditable);
    if (!isOpen() && !typing && (e.key === "g" || e.key === "G")) { e.preventDefault(); open(); }
    else if (isOpen() && e.key === "Escape") { e.preventDefault(); close(); }
  });
})();`
