package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

const generatedMarker = "<!-- generated by Onyx; do not edit -->"

const publicMarker = ".onyx-generated"

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout, stderr io.Writer) int {
	if err := runErr(args, stdout, stderr); err != nil {
		fmt.Fprintf(stderr, "onyx: %v\n", err)
		return 1
	}
	return 0
}

func runErr(args []string, stdout, stderr io.Writer) error {
	if len(args) > 1 {
		return errors.New("usage: onyx [site-root-or-child]")
	}

	start := "."
	if len(args) == 1 {
		start = args[0]
	}

	root, configPath, err := findConfig(start)
	if err != nil {
		return err
	}

	cfg, err := readConfig(root, configPath)
	if err != nil {
		return err
	}

	result, err := buildSite(cfg)
	if err != nil {
		return err
	}
	for _, warning := range result.Warnings {
		fmt.Fprintf(stderr, "warning: %s\n", warning)
	}
	fmt.Fprintf(stdout, "Onyx built %d pages into %s\n", result.Pages, filepath.Join(cfg.Root, "public"))
	return nil
}
